server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${cloud.datasource.driver-class-name}
      url: jdbc:mysql://${cloud.datasource.host}:${cloud.datasource.port}/${cloud.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${cloud.datasource.username}
      password: ${cloud.datasource.password}
  redis:
    host: ${cloud.redis.host}
    port: ${cloud.redis.port}
    password: ${cloud.redis.password}
    database: ${cloud.redis.database}


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      cloud:
        mapper: info
        service: info
        controller: info
        task: info

cloud:
  jwt:
    admin-secret-key: ${cloud.jwt.admin-secret-key}
    admin-ttl: ${cloud.jwt.admin-ttl}
    admin-token-name: ${cloud.jwt.admin-token-name}
    user-secret-key: ${cloud.jwt.user-secret-key}
    user-ttl: ${cloud.jwt.user-ttl}
    user-token-name: ${cloud.jwt.user-token-name}

  alioss:
    endpoint: ${cloud.alioss.endpoint}
    access-key-id: ${cloud.alioss.access-key-id}
    access-key-secret: ${cloud.alioss.access-key-secret}
    bucket-name: ${cloud.alioss.bucket-name}

  wechat:
    appid: ${cloud.wechat.appid}
    secret: ${cloud.wechat.secret}
    mchid: ${cloud.wechat.mchid}
    mchSerialNo: ${cloud.wechat.mchSerialNo}
    privateKeyFilePath: ${cloud.wechat.privateKeyFilePath}
    apiV3Key: ${cloud.wechat.apiV3Key}
    weChatPayCertFilePath: ${cloud.wechat.weChatPayCertFilePath}
    notifyUrl: ${cloud.wechat.notifyUrl}
    refundNotifyUrl: ${cloud.wechat.refundNotifyUrl}
